#!/bin/bash

# Download Jamendo album (single tracks not supported yet) in FLAC format (YA RLY!)

inurl="$1"

albumid="`echo "$inurl" | sed -e 's/.\+\/list\/a\([0-9]\+\)\/.\+$/\1/'`"
foldername="`echo "$inurl" | sed -e 's/.\+\/list\/a\([0-9]\+\)\/\(.\+\)$/\1_\2/'`"

# get metadata
artist_name="`wget -O - -q "http://api.jamendo.com/get2/artist_name/album/plain/?album_id=$albumid"`"
album_name="`wget -O - -q "http://api.jamendo.com/get2/name/album/plain/?album_id=$albumid"`"

#echo "$albumid $foldername" #debug

targetdir="./$foldername"
mkdir -p "$targetdir"

trackn=1
( wget -O - -q "http://api.jamendo.com/get2/stream+name/track/plain/album_track/?n=100&order=numalbum_asc&streamencoding=flac&album_id=$albumid"; echo '' ) | while read track_url track_name; do
	#sleep 2
	if [ "x$track_url" == "x" ]; then
		break
	fi
	track_name_safe="`echo "$track_name" | tr -c 'a-zA-Z0-9' '_'`"
	tracknp=$trackn
	if [ $trackn -lt 10 ]; then
		tracknp=0$trackn
	fi

    	trackfile="$targetdir/${tracknp}_${track_name_safe}.flac"
    	wget -c -O $trackfile "$track_url"

    	# set metadata
    	id3v2 -a "$artist_name" -A "$album_name" -t "$track_name" -T $trackn "$trackfile"

	trackn=$[$trackn+1]
done
