#!/bin/bash

get_flac_tag() {
	metaflac --show-tag="$1" "$2" | sed -e 's/.*=//g'
}

normalize_title() {
	echo -n "$1" | sed -e 'y/ąćęłńóśżźĄĆĘŁŃÓŚŻŹ/acelnoszzACELNOSZZ/' | tr -c 'a-zA-Z0-9' '_'
}

find . -type l -or -type f | while read flac; do
	artist="$(normalize_title "$(get_flac_tag ARTIST "$flac")")"
	title="$(normalize_title "$(get_flac_tag TITLE "$flac")")"
	if [ "x$artist" == "x" ]; then
		continue
	fi
	if [ "x$title" == "x" ]; then
		continue
	fi
	mv "$flac" "$(dirname "$flac")/${artist}_-_${title}.flac"
done
