#!/bin/bash

# SRBDConv - high-quality SampleRate and BitDepth CONVersion tool for FLAC files.
# Preserves tags and file names.

# Requirements: 
#  - sndfile-resample for sinc-interpolated SRC
#  - sox for dithered bits-per-sample conversion
#  - metaflac for saving and restoring tags

[ "x$bitdepth" == "x" ] && bitdepth=16
[ "x$samplerate" == "x" ] && samplerate=44100
[ "x$channels" == "x" ] && channels=2
[ "x$srcq" == "x" ] && srcq=1

[ "x$destdir" == "x" ] && destdir="${samplerate}_${bitdepth}"
mkdir -p "$destdir"

for inflac in $*; do
	tempwav="`mktemp --tmpdir conv_XXXXX.wav`"
	tagfile="`mktemp --tmpdir conv_XXXXX.txt`"
	partialflac="${destdir}/.`basename "${inflac}"`.tmp"
	outflac="${destdir}/`basename "${inflac}"`"

	echo "$inflac >>> $outflac"
	metaflac --export-tags-to="$tagfile" "$inflac"
	sndfile-resample -to $samplerate -c $srcq "$inflac" "$tempwav"
	sox "$tempwav" -b $bitdepth -e signed-integer -c $channels --endian little -t raw - dither -s | flac --force-raw-format --endian=little --bps=$bitdepth --sample-rate=$samplerate --sign=signed --channels=$channels --no-seektable --padding=7200 -o "$partialflac" -
	metaflac --import-tags-from="$tagfile" "$partialflac"
	#metaflac --remove-replay-gain "$partialflac"
	#metaflac --add-replay-gain "$partialflac"
	metaflac --add-seekpoint=64x "$partialflac"
	mv "$partialflac" "$outflac"
	rm -f "$tempwav" "$tagfile"
done

