#!/bin/bash

# SRBDConv - high-quality SampleRate and BitDepth CONVersion tool for FLAC files.
# Preserves tags and file names.

# Requirements: 
#  - sox
#  - metaflac

[ "x$bitdepth" == "x" ] && bitdepth=16
[ "x$samplerate" == "x" ] && samplerate=44100
[ "x$channels" == "x" ] && channels=2
#[ "x$srcq" == "x" ] && srcq=1

[ "x$destdir" == "x" ] && destdir="${samplerate}_${bitdepth}"
mkdir -p "$destdir"

while [ "x$1" != "x" ]; do
	inflac="$1"
	shift
	tagfile="`mktemp --tmpdir conv_XXXXX.txt`"
	partialflac="${destdir}/.`basename "${inflac}"`.tmp"
	outflac="${destdir}/`basename "${inflac}"`"

	echo "$inflac >>> $outflac"
	metaflac --export-tags-to="$tagfile" "$inflac"

	sox --replay-gain off -V -S "$inflac" -r $samplerate -b $bitdepth -e signed-integer -c $channels --endian little -t raw - rate -h dither | flac --force-raw-format --endian=little --bps=$bitdepth --sample-rate=$samplerate --sign=signed --channels=$channels --padding=$[9400+$(wc -c < "$tagfile")] -7 -o "$partialflac" -

	metaflac --add-seekpoint=100x "$partialflac"
	metaflac --import-tags-from="$tagfile" "$partialflac"
	
	#metaflac --remove-replay-gain "$partialflac"
	#metaflac --add-replay-gain "$partialflac"
	mv "$partialflac" "$outflac"
	rm -f "$tagfile"
done

